# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import pel_pb2 as pel__pb2


class PolicyEnforcementStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InspectText = channel.unary_unary(
                '/pel.PolicyEnforcement/InspectText',
                request_serializer=pel__pb2.TextRequest.SerializeToString,
                response_deserializer=pel__pb2.InspectResponse.FromString,
                )
        self.InspectImage = channel.unary_unary(
                '/pel.PolicyEnforcement/InspectImage',
                request_serializer=pel__pb2.ImageRequest.SerializeToString,
                response_deserializer=pel__pb2.InspectResponse.FromString,
                )


class PolicyEnforcementServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InspectText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InspectImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PolicyEnforcementServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InspectText': grpc.unary_unary_rpc_method_handler(
                    servicer.InspectText,
                    request_deserializer=pel__pb2.TextRequest.FromString,
                    response_serializer=pel__pb2.InspectResponse.SerializeToString,
            ),
            'InspectImage': grpc.unary_unary_rpc_method_handler(
                    servicer.InspectImage,
                    request_deserializer=pel__pb2.ImageRequest.FromString,
                    response_serializer=pel__pb2.InspectResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pel.PolicyEnforcement', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PolicyEnforcement(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InspectText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pel.PolicyEnforcement/InspectText',
            pel__pb2.TextRequest.SerializeToString,
            pel__pb2.InspectResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InspectImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pel.PolicyEnforcement/InspectImage',
            pel__pb2.ImageRequest.SerializeToString,
            pel__pb2.InspectResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
