# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/pel.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'proto/pel.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fproto/pel.proto\x12\x03pel\"/\n\x0bTextRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"I\n\x0cImageRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x12\n\nimage_data\x18\x02 \x01(\x0c\x12\x11\n\tmime_type\x18\x03 \x01(\t\"B\n\x0fInspectResponse\x12\x12\n\nrisk_score\x18\x01 \x01(\x02\x12\x1b\n\x06\x61\x63tion\x18\x02 \x01(\x0e\x32\x0b.pel.Action**\n\x06\x41\x63tion\x12\t\n\x05\x41LLOW\x10\x00\x12\n\n\x06REDACT\x10\x01\x12\t\n\x05\x42LOCK\x10\x02\x32\x83\x01\n\x11PolicyEnforcement\x12\x35\n\x0bInspectText\x12\x10.pel.TextRequest\x1a\x14.pel.InspectResponse\x12\x37\n\x0cInspectImage\x12\x11.pel.ImageRequest\x1a\x14.pel.InspectResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.pel_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACTION']._serialized_start=216
  _globals['_ACTION']._serialized_end=258
  _globals['_TEXTREQUEST']._serialized_start=24
  _globals['_TEXTREQUEST']._serialized_end=71
  _globals['_IMAGEREQUEST']._serialized_start=73
  _globals['_IMAGEREQUEST']._serialized_end=146
  _globals['_INSPECTRESPONSE']._serialized_start=148
  _globals['_INSPECTRESPONSE']._serialized_end=214
  _globals['_POLICYENFORCEMENT']._serialized_start=261
  _globals['_POLICYENFORCEMENT']._serialized_end=392
# @@protoc_insertion_point(module_scope)
